_specver: 2

modpack:
  name: Craftoria
  description: The latest & best of NeoForge on 1.21
  
install:
  mcVersion:
  loaderVersion: 21.0.17-beta
  modpackUrl: https://mediafilez.forgecdn.net/files/5441/979/Craftoria-0.0.2.zip
  installerUrl: "https://maven.neoforged.net/releases/net/neoforged/neoforge/{{@loaderversion@}}/neoforge-{{@loaderversion@}}-installer.jar"
  
  ignoreFiles:
    - mods/optifine*.jar
    - resources/**
  additionalFiles:
  localFiles: ~
  
  installerArguments:
    - "--installServer"
  modpackFormat: curse
  
  formatSpecific:
    ignoreProject: 
      - 472772 # Dashloader
      
  baseInstallPath: 
  
  checkFolder: true
  
  installLoader: true
  
  installPack: true
  
  spongeBootstrapper: ~

  connectTimeout: 90

  readTimeout: 90

launch:
  # specifies the max amount of ram the server is supposed to launch with (Xmx)
  maxRam: 5G
  # specifies the minimal amount of ram the server is supposed to launch with (Xms)
  minRam: 3G
  # specifies whether the server is supposed to auto restart after crash
  autoRestart: false
  javaArgs:
    - "-XX:+UseG1GC"
    
  spongefix: false
  ramDisk: false
  checkOffline: false
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  forcedJavaPath: ~
  startCommand: 
    - "@libraries/net/neoforged/neoforge/{{@loaderversion@}}/{{@os@}}_args.txt"
    - "nogui"
    - "-jar"
    - "libraries/net/neoforged/neoforge/{{@loaderversion@}}/neoforge-{{@loaderversion@}}-server.jar"
