#List of ranks
[[ranks]]
	tier = 1
	numAffixes = 0
	defaultColor = "#FFC0CB"
	chance = 0.2
	growthFactor = 0
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 2
	numAffixes = 1
	defaultColor = "#FFFF00"
	chance = 0.2
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 3
	numAffixes = 2
	defaultColor = "#FF9900"
	chance = 0.2
	growthFactor = 4
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 4
	numAffixes = 3
	defaultColor = "#66FFFF"
	chance = 0.2
	growthFactor = 9
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 5
	numAffixes = 4
	defaultColor = "#CC33FF"
	chance = 0.2
	growthFactor = 16
	effects = []
	presetAffixes = []
